language: java
dist: trusty
before_install:
- curl -O http://central.maven.org/maven2/org/python/jython-installer/2.7.1b3/jython-installer-2.7.1b3.jar
- java -jar jython-installer-2.7.1b3.jar -s -d /tmp/jython
- "/tmp/jython/bin/jython --version"
- mkdir -p ~/.gradle
- echo jythonInterpreter=/tmp/jython/bin/jython >> ~/.gradle/gradle.properties
deploy:
  provider: releases
  api_key:
    secure: kQYB4gHl0IK4HrDY6FOwze3/9HGdtIHJCJ+gedjxz5IDP58j0ToB4ZD5w+7oiflWJAr7B2RKPF+lQjOol49Nexp5/erfQOWrfArYpYaW1sQ7xz9DaYBzpMoV073Pz4ajCHqGL+l3diurx6Shh5pLuGTYgq+HFXkbf48gvAlhcIj0ocHkO9oMHhLk0nPKQ4vrHZTC3CZr7sZpGfalFSIYGYRU+iPZ7DuCdtbxR5zDHLr6Jj95zxu9SUgb6fI98sbFSCulVm++gxCdu639v63tnvtxRcONBIEVcS0EgwawS48hOPG1I/8OCIfTagZsL98te12+aOHCQWUGbzt4uW23mhizCvQk+DJyit9LvyU7eztGxziFHkEFwG/b8KTCEqgwqNSmcPcTXj+//511aHeFwJFtbsMCSrJroXxRwRlGgvysBwOKVubzN+eJXEUN2X5H7ypLnU8kWVu7j0/XLmTzvCA7JjEm+AP2BZas31l5OmHffR2AhthLk1MZB+aMINYlcNaxLvbGsnnhkpfB49GGvfjsth8IVPlLeAUJCo1eH2W23UmVi/RD9mGXb+f617ZGWXzuF6UuYAU0mCwZKYBxLJp/SXv9xvKvfRRyh7FZsuEovXVV/pRuPHQozZhEwiR/WnodB+iVPwjHsG4Cbea6XEyn19DeLar4WD+DMwtCKDc=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    repo: xebialabs-community/xlr-import-csv-template-plugin
    all_branches: true
    tags: true
notifications:
  slack:
    secure: vl+jco0TpJHiQGzZeFWXvXdKX0tc5C5+FkLLkKCzOflMLGP6AVN29hSXkB8nbf1aHSboxc0KRRxvBtjC5P47D1fXLx5vi05rbi5W5lSoKpqp7/o8hfA18mHu3knWRITFRQ1ocdVCBcGHQAQ90uJcJ4m8YClLdfaEqgsbaeFiACEgNidVQqBQLorMDumITCjmjqmO8+4se127L9YXEJK8M6qjSyYsvD8UCs9cg8FvK0zMddqEjvuOVaGXrQFMzawttKuLtMFk+s36mT9GKeZBKmZbynjB4omqwmFDGsUQKnV0CNGjQoxxpeN+qU3ZVs16gITi0qFslTb0X2w9d9omevLrf8NQaqBSWegEGB+7h69Qdd2VtMoZAEwzrGqys+Bx2PSMeHDHRD9KJMKltVGq/6187KpcAWH+Fv41RPJ9YsoFIleUHFBhuYYPQp3+nRzD3OvT7iBJQ/h7QokBqcFZjjYuSh09dWcXZ6XAlYwZbpoIIf8qOe2YfTdP3VPAXeRW3W1JVM8jv0jfeHyVSXSPV4WWfJyfWIhuQiI+zP7obcwZkHlfgHJNKV/YL0PpXcnRy2dluCRtHfZCU9r761x97cu+8xNmZbuo6P6dBBdlism+osFM8+wE51HmGnvccjFX5vhwCm1jJUL/YZsO0lkpdUUSh8LC1PWOYdLiultxRL0=
